version: "3"

networks:
  web:
    external: true

services:
  traefik:
    image: traefik:v2.2
    restart: always    
    ports:
      - 80:80
      - 443:443
    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json    
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:monitor.devops-test.ru
      - traefik.port=9090
    networks:
      - web

  site1:
    image: nginx:alpine
    restart: always

    labels:
      - traefik.backend=site1
      - traefik.frontend.rule=Host:site1.devops-test.ru
      - traefik.docker.network=web
      - traefik.port=80

    volumes:
      - ./site1/hosts:/etc/nginx/conf.d
      - ./site1/www:/var/www
      - ./site1/logs:/var/log/nginx
    networks:
      - web
    depends_on:
      - traefik

  site2:
    image: nginx:alpine
    restart: always

    labels:
      - traefik.backend=site2
      - traefik.frontend.rule=Host:site2.devops-test.ru
      - traefik.docker.network=web
      - traefik.port=80

    volumes:
      - ./site2/hosts:/etc/nginx/conf.d
      - ./site2/www:/var/www
      - ./site2/logs:/var/log/nginx
    networks:
      - web
    depends_on:
      - traefik


